# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestDAY16Q1():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_dAY16Q1(self):
    self.driver.get("https://tutorialsninja.com/demo/index.php?route=account/register")
    self.driver.set_window_size(1280, 800)
    self.driver.find_element(By.ID, "input-firstname").send_keys("Preetam")
    self.driver.find_element(By.ID, "input-lastname").send_keys("prabhakaran")
    self.driver.find_element(By.ID, "input-email").send_keys("preetam@example.com")
    self.driver.find_element(By.CSS_SELECTOR, "input#input-telephone").send_keys("9876617322")
    self.driver.find_element(By.XPATH, "//input[@id=\'input-password\']").send_keys("Test@456")
    self.driver.find_element(By.XPATH, "//input[@id=\'input-confirm\']").send_keys("Test@456")
    self.driver.find_element(By.XPATH, "//input[@name=\'newsletter\' and @value=\'1\']").click()
    self.driver.find_element(By.NAME, "agree").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn-primary").click()
    time.sleep(2)
    assert self.driver.find_element(By.XPATH, "//h1[text()=\'Your Account Has Been Created!\']").text == "Your Account Has Been Created!"
    print("Your Account Has Been Created!")
    self.driver.close()
  
