# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

from day18_class_work.Lab_11.locators import Lab_11_Locators


class TestLab11TestSuite():
    def setup_method(self, method):
        self.driver = webdriver.Chrome()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_lab11(self):
        self.driver.get("https://tutorialsninja.com/demo/")
        self.driver.set_window_size(1296, 688)

        assert self.driver.title == "Your Store"

        self.driver.find_element(*Lab_11_Locators.desktops_link).click()
        self.driver.find_element(*Lab_11_Locators.mac_link).click()

        assert self.driver.find_element(*Lab_11_Locators.mac_heading).text == "Mac"

        self.driver.find_element(*Lab_11_Locators.sort_dropdown).click()
        self.driver.find_element(*Lab_11_Locators.sort_name_AZ).click()

        self.driver.execute_script("window.scrollTo(0,356)")
        self.driver.find_element(*Lab_11_Locators.add_to_cart).click()

        self.driver.execute_script("window.scrollTo(0,413.3333435058594)")

        self.driver.find_element(*Lab_11_Locators.search_box).click()
        self.driver.find_element(*Lab_11_Locators.search_box).send_keys("Monitors")
        self.driver.find_element(*Lab_11_Locators.search_button).click()

        WebDriverWait(self.driver, 30).until(
            expected_conditions.visibility_of_element_located((By.CSS_SELECTOR, "h1"))
        )

        self.driver.find_element(*Lab_11_Locators.search_box).clear()
        self.driver.find_element(*Lab_11_Locators.search_box).send_keys("Monitors")
        self.driver.find_element(*Lab_11_Locators.description_checkbox).click()
        self.driver.find_element(*Lab_11_Locators.search_submit).click()

    def test_lab11searchonly(self):
        self.driver.get("https://tutorialsninja.com/demo/")
        self.driver.set_window_size(1296, 688)

        assert self.driver.title == "Your Store"

        self.driver.find_element(*Lab_11_Locators.search_box).click()
        self.driver.find_element(*Lab_11_Locators.search_box).send_keys("Monitors")
        self.driver.find_element(*Lab_11_Locators.search_button).click()

        assert self.driver.find_element(By.CSS_SELECTOR, "label.control-label").text == "Search Criteria"
