# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestDay15Q2():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_day15Q2(self):
    self.driver.get("https://practicetestautomation.com/practice-test-login/")
    self.driver.set_window_size(1296, 688)
    self.driver.find_element(By.ID, "username").click()
    self.driver.find_element(By.ID, "username").send_keys("student")
    self.driver.find_element(By.ID, "password").click()
    self.driver.find_element(By.ID, "password").send_keys("Password123")
    self.driver.find_element(By.ID, "submit").click()
    time.sleep(1)
    assert self.driver.title == "Logged In Successfully | Practice Test Automation"
    assert self.driver.find_element(By.CSS_SELECTOR, ".post-title").text == "Logged In Successfully"
    self.driver.close()
  
