# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestDay16Q2():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_day16Q2(self):
    self.driver.get("https://www.amazon.in/")
    self.driver.set_window_size(1280, 800)
    self.vars["homeTitle"] = self.driver.title
    print("{}".format(self.vars["homeTitle"]))
    self.driver.find_element(By.ID, "nav-link-accountList").click()
    time.sleep(1)
    self.vars["loginTitle"] = self.driver.title
    print("{}".format(self.vars["loginTitle"]))
    self.driver.get("https://www.amazon.in/")
    self.vars["backTitle"] = self.driver.title
    print("{}".format(self.vars["backTitle"]))
    self.driver.get("https://www.amazon.in/ap/signin")
    self.vars["forwardTitle"] = self.driver.title
    print("{}".format(self.vars["forwardTitle"]))
    self.driver.get("https://www.amazon.in/ap/signin")
    self.vars["refreshTitle"] = self.driver.title
    print("{}".format(self.vars["refreshTitle"]))
  
