# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestLab4():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_lab4(self):
    self.driver.get("https://demo.opencart.com/")
    self.driver.set_window_size(1296, 688)
    assert self.driver.title == "Your Store"
    self.driver.find_element(By.LINK_TEXT, "Desktops").click()
    self.driver.find_element(By.LINK_TEXT, "Mac (1)").click()
    self.driver.find_element(By.ID, "input-sort").click()
    dropdown = self.driver.find_element(By.ID, "input-sort")
    dropdown.find_element(By.XPATH, "//option[. = 'Name (A - Z)']").click()
    self.driver.execute_script("window.scrollTo(0,436)")
    self.driver.find_element(By.CSS_SELECTOR, ".fa-shopping-cart").click()
    self.driver.find_element(By.NAME, "search").click()
    self.driver.find_element(By.NAME, "search").send_keys("Mobile")
    self.driver.find_element(By.CSS_SELECTOR, ".fa-magnifying-glass").click()
    time.sleep(2)
    self.driver.find_element(By.NAME, "search").click()
    self.driver.find_element(By.NAME, "search").send_keys(" ")
    self.driver.find_element(By.ID, "input-description").click()
    self.driver.find_element(By.ID, "button-search").click()
  
